name: photo_player
description: Advanced photo and video player app

publish_to: 'none'

version: 2.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  video_player: ^2.8.1
  path: ^1.8.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  audioplayers: ^5.2.1
  path_provider: ^2.1.1
  
  # 使用兼容的版本
  sqflite: ^2.2.8+4
  wakelock_plus: ^1.1.4
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
